module.exports=require("../../_commons/0.js")([{ids:[6],modules:{"./node_modules/@mpflow/webpack-plugin/lib/loaders/page-loader.js?appContext=src&outputPath=components%2Fpage-scroll%2Findex!./src/components/page-scroll/index.ts":
/*!*************************************************************************************************************************************************************************!*\
      !*** ./node_modules/@mpflow/webpack-plugin/lib/loaders/page-loader.js?appContext=src&outputPath=components%2Fpage-scroll%2Findex!./src/components/page-scroll/index.ts ***!
      \*************************************************************************************************************************************************************************/
/*! no static exports found */
function(e,o,t){e.exports=t(/*! ./index.ts */"./src/components/page-scroll/index.ts")},"./src/components/page-scroll/index.ts":
/*!*********************************************!*\
      !*** ./src/components/page-scroll/index.ts ***!
      \*********************************************/
/*! no static exports found */
function(e,o){Component({options:{virtualHost:!0},properties:{refresherEnabled:{type:Boolean,value:!1},refresherThreshold:{type:Number,value:45},refresherDefaultStyle:{type:String,value:"black"},refresherBackground:{type:String,value:"#FFF"},refresherTriggered:{type:Boolean,value:!1},lowerThreshold:{type:Number,value:50},scrollIntoView:{type:String,value:""}},methods:{onScroll:function(e){this.triggerEvent("scroll",e.detail)},onScrollToLower:function(e){this.triggerEvent("scrollToLower",e.detail)},onPulling:function(e){this.triggerEvent("pulling",e.detail)},onRefresh:function(e){this.triggerEvent("refresh",e.detail)},onRestore:function(e){this.triggerEvent("restore",e.detail)},onAbort:function(e){this.triggerEvent("abort",e.detail)}}})}},entries:[["./node_modules/@mpflow/webpack-plugin/lib/loaders/page-loader.js?appContext=src&outputPath=components%2Fpage-scroll%2Findex!./src/components/page-scroll/index.ts",0]]}]);